"""add performance indexes

Revision ID: 0640f3930f4e
Revises: 
Create Date: 2026-02-24 21:53:40.283782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0640f3930f4e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alert', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alert_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_alert_timestamp'), ['timestamp'], unique=False)

    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_answer_session_id'), ['session_id'], unique=False)

    with op.batch_alter_table('exam_session', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exam_session_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_exam_session_student_id'), ['student_id'], unique=False)

    with op.batch_alter_table('invigilator', schema=None) as batch_op:
        batch_op.alter_column('reset_token',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)

    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_question_exam_name'), ['exam_name'], unique=False)

    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.alter_column('reset_token',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_student_cohort'), ['cohort'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_student_cohort'))
        batch_op.alter_column('reset_token',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_question_exam_name'))

    with op.batch_alter_table('invigilator', schema=None) as batch_op:
        batch_op.alter_column('reset_token',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('exam_session', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exam_session_student_id'))
        batch_op.drop_index(batch_op.f('ix_exam_session_status'))

    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_answer_session_id'))

    with op.batch_alter_table('alert', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alert_timestamp'))
        batch_op.drop_index(batch_op.f('ix_alert_session_id'))

    # ### end Alembic commands ###
