"""add admin fields

Revision ID: cf659f9202d3
Revises: 0640f3930f4e
Create Date: 2026-03-03 12:49:49.422539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf659f9202d3'
down_revision = '0640f3930f4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_invigilator')
    with op.batch_alter_table('invigilator', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admin_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('assigned_cohorts', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))
        batch_op.alter_column('reset_token',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.create_foreign_key(None, 'admins', ['admin_id'], ['id'])

    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_question_exam_name'), ['exam_name'], unique=False)

    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.alter_column('reset_token',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_student_cohort'), ['cohort'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_student_cohort'))
        batch_op.alter_column('reset_token',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_question_exam_name'))

    with op.batch_alter_table('invigilator', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('reset_token',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.drop_column('is_active')
        batch_op.drop_column('assigned_cohorts')
        batch_op.drop_column('admin_id')

    op.create_table('_alembic_tmp_invigilator',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('email', sa.VARCHAR(length=100), nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=200), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('reset_token', sa.VARCHAR(length=100), nullable=True),
    sa.Column('reset_token_expiry', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###
